# Generated by Django 3.1.3 on 2021-01-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('subtitle', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=200)),
                ('price', models.BigIntegerField(max_length=100)),
                ('genre', models.CharField(max_length=15)),
                ('author', models.CharField(max_length=20)),
                ('year', models.DateField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
