# Generated by Django 3.1.3 on 2021-01-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='library',
            name='year',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
