# Generated by Django 3.1.3 on 2021-01-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_library_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
